export const config = {
  port: parseInt(process.env.API_PORT || "4000", 10),
  jwtSecret: process.env.JWT_SECRET || "dev-only-secret-change-me",
  jwtRefreshSecret: process.env.JWT_REFRESH_SECRET || "dev-only-refresh-secret",
  corsOrigin: process.env.CORS_ORIGIN || "http://localhost:3000",
  accessTokenTtl: "15m",
  refreshTokenTtlDays: 30,
  stripeSecretKey: process.env.STRIPE_SECRET_KEY || "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET || "",
  jazzcashMerchantId: process.env.JAZZCASH_MERCHANT_ID || "",
  jazzcashPassword: process.env.JAZZCASH_PASSWORD || "",
  easypaisaMerchantId: process.env.EASYPAISA_MERCHANT_ID || "",
  easypaisaEndpoint: process.env.EASYPAISA_ENDPOINT || "",
  apiBaseUrl: process.env.API_BASE_URL || "http://localhost:4000",
  googleClientId: process.env.GOOGLE_CLIENT_ID || "",
  facebookAppId: process.env.FACEBOOK_APP_ID || "",
  appleClientId: process.env.APPLE_CLIENT_ID || "",
};
